apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.projectName }}-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccountName }}