name: 'Helm Deployment'
description: 'Generic template to deploy to dev and prod envs'
inputs:
  environment:
    description: 'environment to deploy'
    required: true
    default: 'dev'
  imageTag:
    description: 'Docker image to be added in the helm deployment'
  gkeCluster:
    description: 'Cluster name to deploy to'
  region:
    description: 'GCP region'
  helmChartName:
    description: 'Helm chart name'
  domain:
    description: 'domain to be associated'

runs:
  using: "composite"
  steps:
  - id: auth
    name: 'Authenticate to Google Cloud'
    uses: 'google-github-actions/auth@v1'
    with:
      #token_format: 'access_token'
      workload_identity_provider: 'projects/689152611462/locations/global/workloadIdentityPools/deel-github-pool/providers/deel-gha-provider'
      service_account: 'deel-service-gha@deel-368916.iam.gserviceaccount.com '
  - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v1'
  - name: Install Helm
    shell: bash
    run: |
      gcloud components install gke-gcloud-auth-plugin
      curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  # Deploy the Docker image to the GKE cluster
  - name: Helm Deploy 
    shell: bash
    run: |
      gcloud container clusters get-credentials ${{ inputs.gkeCluster }} \
        --region ${{ inputs.region }}
      
      helm upgrade --install -n ${{ inputs.environment }} ${{ inputs.helmchartName }} \
        ./chart \
        --set imageTag=${{ inputs.imageTag }},domain=${{ inputs.domain}}