name: 'Helm Deployment'
description: 'Generic template to deploy to dev and prod envs'
inputs:
  environment: 
    description: 'environment to deploy'
    required: true
    default: 'dev'
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.environment}}.
      shell: bash